In [1]:
import pandas as pd
import glob
import os

In [2]:
files = glob.glob(
    "../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)/*.csv"
)

len(files)

98

In [3]:
files[:10]

['../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)\\backpacks.csv',
 '../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)\\bath-robe.csv',
 '../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)\\bath-towels.csv',
 '../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)\\bathroom-accessories.csv',
 '../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)\\bedsheets.csv',
 '../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)\\belts.csv',
 '../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)\\bodysuit.csv',
 '../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)\\boots.csv',
 '../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)\\boxers.csv',
 '../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)\\bra.csv']

In [4]:
df_test = pd.read_csv(files[0])

In [5]:
df_test.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks

In [6]:
df_test.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              4 non-null      int64
 1   title                   4 non-null      object
 2   product_description     4 non-null      object
 3   rating                  4 non-null      float64
 4   ratings_count           4 non-null      int64
 5   initial_price           4 non-null      float64
 6   discount                4 non-null      float64
 7   final_price             4 non-null      object
 8   currency                4 non-null      object
 9   images                  4 non-null      object
 10  delivery_options        4 non-null      object
 11  product_details         4 non-null      object
 12  breadcrumbs             4 non-null      object
 13  product_specifications  4 non-null      object
 14  amount_of_stars         4 non-null      object
 15  what_customers_said     0 non-null      float64
 16  seller_name             0 non-null      float64
 17  sizes                   4 non-null      object
 18  videos                  4 non-null      object
 19  seller_information      0 non-null      float64
 20  variations              3 non-null      object
 21  best_offer              4 non-null      object
 22  more_offers             4 non-null      object
 23  category                4 non-null      object
dtypes: float64(6), int64(2), object(16)
memory usage: 900.0+ bytes

In [7]:
column_check = {}

for file in files:
    temp = pd.read_csv(file)
    column_check[os.path.basename(file)] = list(temp.columns)

In [8]:
unique_structures = set(
    tuple(columns) for columns in column_check.values()
)

len(unique_structures)

1

In [9]:
df_list = []

for file in files:
    temp = pd.read_csv(file)
    df_list.append(temp)

df = pd.concat(df_list, ignore_index=True)

In [10]:
from pathlib import Path
import pandas as pd

folder = Path(
    "../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)"
)

csv_files = list(folder.glob("*.csv"))

print("CSV files found:", len(csv_files))

dataframes = [pd.read_csv(file) for file in csv_files]

df = pd.concat(dataframes, ignore_index=True)

print("Combined shape:", df.shape)

CSV files found: 98
Combined shape: (2000, 24)

In [11]:
df_list = []

for file in files:
    temp = pd.read_csv(file)
    df_list.append(temp)

df = pd.concat(df_list, ignore_index=True)

In [12]:
df.shape

(2000, 24)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              2000 non-null   int64
 1   title                   2000 non-null   object
 2   product_description     2000 non-null   object
 3   rating                  2000 non-null   float64
 4   ratings_count           2000 non-null   int64
 5   initial_price           2000 non-null   float64
 6   discount                1758 non-null   float64
 7   final_price             2000 non-null   object
 8   currency                2000 non-null   object
 9   images                  2000 non-null   object
 10  delivery_options        2000 non-null   object
 11  product_details         2000 non-null   object
 12  breadcrumbs             2000 non-null   object
 13  product_specifications  2000 non-null   object
 14  amount_of_stars         2000 non-null   object
 15  what_customers_said     854 non-null    object
 16  seller_name             1398 non-null   object
 17  sizes                   2000 non-null   object
 18  videos                  438 non-null    object
 19  seller_information      1398 non-null   object
 20  variations              876 non-null    object
 21  best_offer              2000 non-null   object
 22  more_offers             2000 non-null   object
 23  category                2000 non-null   object
dtypes: float64(3), int64(2), object(19)
memory usage: 375.1+ KB

In [14]:
df.describe()

         product_id       rating  ratings_count  initial_price     discount
count  2.000000e+03  2000.000000    2000.000000    2000.000000  1758.000000
mean   1.713437e+07     3.621500      76.691000    2723.241000    53.503982
std    3.812812e+06     1.374057     241.053946    2408.094809    18.024070
min    5.868460e+05     0.000000       0.000000     249.000000     1.000000
25%    1.511501e+07     3.700000       7.000000    1399.000000    44.000000
50%    1.820890e+07     4.100000      17.000000    1999.000000    56.000000
75%    1.902737e+07     4.300000      58.000000    3299.000000    66.000000
max    2.274707e+07     5.000000    4441.000000   22199.000000    88.000000

In [15]:
df["rating"].value_counts().sort_index()

rating
0.0    228
1.7      2
1.8      2
1.9      2
2.0      2
2.1      2
2.2      2
2.3      6
2.4      2
2.5      2
2.7      8
2.8     12
2.9      6
3.0     20
3.1      4
3.2     26
3.3     30
3.4     20
3.5     42
3.6     38
3.7     88
3.8     98
3.9    128
4.0    164
4.1    180
4.2    180
4.3    210
4.4    166
4.5    122
4.6     76
4.7     42
4.8     38
4.9     20
5.0     32
Name: count, dtype: int64

In [16]:
df["initial_price"].value_counts().sort_index().head(10)

initial_price
249.0    4
265.0    2
294.0    2
299.0    4
319.0    2
329.0    2
339.0    2
345.0    4
379.0    2
390.0    2
Name: count, dtype: int64

In [17]:
df["product_id"].nunique()

1000

In [18]:
df.duplicated().sum()

np.int64(1000)

In [19]:
df[df["product_id"].duplicated(keep=False)].head(10)

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399.0,65.0,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
6,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399.0,NaN,"""₹1,399.00""",INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",NaN,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999.0,54.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
9,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199.0,53.0,"""₹2,199.00""",INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

In [20]:
df["product_id"].value_counts().value_counts()

count
2    1000
Name: count, dtype: int64

In [21]:
df_clean = df.drop_duplicates().copy()

In [22]:
df_clean.shape

(1000, 24)

In [23]:
df_clean["product_id"].nunique()

1000

In [24]:
df_clean

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,"""₹3,995.00""",INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,"""₹2,999.00""",INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,"""₹1,675.00""",INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,"""₹2,899.00""",INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1081,13698258,KREDO,Men FORTE Silver Automatic Skeleton Analogue W...,3.5,11,11890.0,50.0,"""₹11,890.00""",INR,http://assets.myntassets.com/assets/images/136...,...,"{""1_star"":3,""2_stars"":0,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""pi-13698258""]",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1082,16896006,GUESS,Women White Patterned Dial & White Straps Anal...,5.0,22,8900.0,45.0,"""₹8,900.00""",INR,http://assets.myntassets.com/assets/images/168...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-16896006_cae700"",""https://videos.myntasse...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1083,1708108,GIORDANO,Women Rose Gold-Toned Mirrored Analogue Watch ...,2.8,5,7950.0,50.0,"""₹7,950.00""",INR,http://assets.myntassets.com/assets/images/170...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",watches
1084,19280114,Fastrack,Men Black Brass Dial & Black Stainless Steel S...,4.3,17,3295.0,20.0,"""₹2,636.00""",INR,http://assets.myntassets.com/assets/images/192...,...,"{""1_star"":1,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,Tru███m R███il,"[{""size"":""Onesize""}]",NaN,Sho███o. ███-10█████████enu███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",watches
1085,18601682,BOLDFIT,Purple Textured Yoga Mat,3.8,161,699.0,31.0,"""₹699.00""",INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":24,""2_stars"":8,""3_stars"":22,""4_stars...",NaN,NaN,"[{""size"":""Medium""}]",NaN,NaN,"[{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",yoga-mats

In [25]:
df_clean.shape

(1000, 24)

In [26]:
df_clean["product_id"].nunique()

1000

In [27]:
df_clean["product_id"].nunique()

1000

In [28]:
df_clean["final_price"].head(10)

0    "₹3,995.00"
1    "₹2,899.00"
2    "₹2,999.00"
3    "₹1,675.00"
4    "₹2,899.00"
5    "₹1,399.00"
6    "₹1,399.00"
7    "₹2,999.00"
8    "₹2,999.00"
9    "₹2,199.00"
Name: final_price, dtype: object

In [29]:
df_clean["final_price"] = (
    df_clean["final_price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace('"', "", regex=False)
    .astype(float)
)

In [30]:
df_clean["final_price"].head(10)

0    3995.0
1    2899.0
2    2999.0
3    1675.0
4    2899.0
5    1399.0
6    1399.0
7    2999.0
8    2999.0
9    2199.0
Name: final_price, dtype: float64

In [31]:
df_clean["final_price"].head(10)

0    3995.0
1    2899.0
2    2999.0
3    1675.0
4    2899.0
5    1399.0
6    1399.0
7    2999.0
8    2999.0
9    2199.0
Name: final_price, dtype: float64

In [32]:
import pandas as pd
import glob
import os

In [33]:
files = glob.glob(
    "../01_Structured Files/Ecommerce Dataset (Products & Sizes Included)/*.csv"
)

len(files)

98

In [34]:
df_list = []

for file in files:
    temp = pd.read_csv(file)
    df_list.append(temp)

df = pd.concat(df_list, ignore_index=True)

In [35]:
df.shape

(2000, 24)

In [36]:
df_clean = df.drop_duplicates().copy()

In [37]:
df_clean["final_price"] = (
    df_clean["final_price"]
    .str.replace("₹", "", regex=False)
    .str.replace(",", "", regex=False)
    .str.replace('"', "", regex=False)
    .astype(float)
)

In [38]:
df_clean.isnull().sum()

product_id                  0
title                       0
product_description         0
rating                      0
ratings_count               0
initial_price               0
discount                  121
final_price                 0
currency                    0
images                      0
delivery_options            0
product_details             0
breadcrumbs                 0
product_specifications      0
amount_of_stars             0
what_customers_said       573
seller_name               301
sizes                       0
videos                    781
seller_information        301
variations                562
best_offer                  0
more_offers                 0
category                    0
dtype: int64

## Missing Value Handling

After removing duplicate product records, the dataset contains missing values in
some optional product information fields such as discount, customer comments,
seller information, videos, and product variations.

These missing values were retained rather than removed or replaced with
artificial values because the absence of information does not necessarily mean
that the product has no such feature. Keeping the values as missing preserves
the original information and avoids introducing assumptions into the analysis.

In [39]:
df_clean["discount"].describe()

count    879.000000
mean      53.503982
std       18.029201
min        1.000000
25%       44.000000
50%       56.000000
75%       66.000000
max       88.000000
Name: discount, dtype: float64

In [40]:
df_clean["discount"].value_counts().sort_index().head(20)

discount
1.0      6
2.0      1
3.0      1
4.0      1
5.0      7
6.0      1
8.0      1
10.0     7
12.0     2
13.0     1
14.0     2
15.0     4
16.0     2
17.0     1
19.0     1
20.0    21
22.0     1
23.0     3
24.0     2
25.0    27
Name: count, dtype: int64

In [41]:
df_clean["discount"].value_counts().sort_index().tail(20)

discount
69.0     8
70.0    38
71.0    10
72.0    11
73.0     9
74.0    24
75.0    20
76.0    16
77.0     3
78.0     8
79.0     5
80.0    11
81.0     7
82.0     5
83.0     2
84.0     2
85.0     5
86.0     1
87.0     1
88.0     3
Name: count, dtype: int64

### Discount Cleaning

discount
├── 879 products → valid discount values ✅
└── 121 products → missing information → keep NaN

The discount column contains 879 valid values ranging from 1% to 88%,
while 121 products have missing discount information.

The available discount values were found to be within a reasonable range,
with no negative or unusually high values. Missing discount values were
retained as NaN because the dataset does not clearly indicate whether a
missing value represents no discount or unavailable discount information.

In [42]:
df_clean["category"].value_counts()

category
tops            122
dresses         100
shirts           97
jeans            57
sports-shoes     51
               ...
tights            1
table-covers      1
swim-tops         1
wall-art          1
yoga-mats         1
Name: count, Length: 97, dtype: int64

In [43]:
top_categories = df_clean["category"].value_counts().head(10)

top_categories

category
tops            122
dresses         100
shirts           97
jeans            57
sports-shoes     51
tshirts          39
earrings         34
sweaters         34
jackets          29
casual-shoes     23
Name: count, dtype: int64

In [44]:
df_clean["category"].value_counts()

category
tops            122
dresses         100
shirts           97
jeans            57
sports-shoes     51
               ...
tights            1
table-covers      1
swim-tops         1
wall-art          1
yoga-mats         1
Name: count, Length: 97, dtype: int64

In [45]:
top_categories = df_clean["category"].value_counts().head(10)
top_categories

category
tops            122
dresses         100
shirts           97
jeans            57
sports-shoes     51
tshirts          39
earrings         34
sweaters         34
jackets          29
casual-shoes     23
Name: count, dtype: int64

In [46]:
category_price = (
    df_clean.groupby("category")["final_price"]
    .mean()
    .sort_values(ascending=False)
    .head(10)
)

category_price

category
trolley-bag     17995.000000
headphones       5832.333333
sherwani         5764.600000
watches          5392.800000
sports-shoes     4228.470588
sunglasses       3480.000000
bath-robe        2899.000000
backpacks        2892.000000
sweatshirts      2838.500000
formal-shoes     2798.416667
Name: final_price, dtype: float64

In [47]:
category_price_analysis = (
    df_clean.groupby("category")
    .agg(
        product_count=("product_id", "count"),
        average_price=("final_price", "mean")
    )
    .sort_values("average_price", ascending=False)
)

category_price_analysis.head(10)

              product_count  average_price
category
trolley-bag               1   17995.000000
headphones                3    5832.333333
sherwani                  5    5764.600000
watches                  15    5392.800000
sports-shoes             51    4228.470588
sunglasses                1    3480.000000
bath-robe                 1    2899.000000
backpacks                 4    2892.000000
sweatshirts              20    2838.500000
formal-shoes             12    2798.416667

In [48]:
reliable_category_price = (
    category_price_analysis[
        category_price_analysis["product_count"] >= 10
    ]
    .sort_values("average_price", ascending=False)
)

reliable_category_price.head(10)

              product_count  average_price
category
watches                  15    5392.800000
sports-shoes             51    4228.470588
sweatshirts              20    2838.500000
formal-shoes             12    2798.416667
flats                    12    2754.583333
casual-shoes             23    2660.782609
jackets                  29    2494.310345
bedsheets                11    2444.545455
jeans                    57    2173.649123
kurtas                   20    1919.450000

In [49]:
category_rating_analysis = (
    df_clean.groupby("category")
    .agg(
        product_count=("product_id", "count"),
        average_rating=("rating", "mean")
    )
)

reliable_category_rating = (
    category_rating_analysis[
        category_rating_analysis["product_count"] >= 10
    ]
    .sort_values("average_rating", ascending=False)
)

reliable_category_rating.head(10)

                product_count  average_rating
category
watches                    15        4.153333
sweaters                   34        4.147059
sports-shoes               51        4.117647
handbags                   18        4.100000
kurtas                     20        3.970000
shirts                     97        3.967010
bra                        13        3.923077
ethnic-dresses             20        3.920000
tshirts                    39        3.876923
sweatshirts                20        3.855000

In [50]:
discount_price_analysis = df_clean[
    ["initial_price", "discount", "final_price"]
].dropna()

discount_price_analysis.head()

   initial_price  discount  final_price
0         3995.0      58.0       3995.0
1         2899.0      35.0       2899.0
2         2999.0      65.0       2999.0
3         1675.0      52.0       1675.0
4         2899.0      17.0       2899.0

In [51]:
discount_price_analysis.corr()

               initial_price  discount  final_price
initial_price       1.000000  0.136656     0.802939
discount            0.136656  1.000000    -0.067643
final_price         0.802939 -0.067643     1.000000

### Discount and Price Analysis

Correlation analysis showed a strong positive relationship between initial price and final price (0.80), meaning higher-priced products generally tend to have higher final prices.

The correlation between discount and final price was very weak (-0.07), indicating that discount percentage has almost no linear relationship with final price in this dataset.

The correlation between discount and initial price was also weak (0.14).

An important data-quality observation is that some products have a discount value even though their initial price and final price are identical. Therefore, the price fields should be interpreted carefully and should not be assumed to perfectly represent the actual discounted selling price.

In [52]:
rating_review_analysis = df_clean[
    ["rating", "ratings_count"]
].copy()

rating_review_analysis.corr()

                 rating  ratings_count
rating         1.000000       0.125795
ratings_count  0.125795       1.000000

### Rating and Review Count Analysis

The correlation between product rating and ratings count is approximately 0.126, indicating a very weak positive relationship.

This means products with more reviews may have slightly higher ratings on average, but the relationship is not strong enough to conclude that a higher number of reviews leads to a higher rating.

Therefore, review count and product rating appear to be largely independent in this dataset.

In [53]:
best_products = (
    df_clean[df_clean["ratings_count"] >= 10]
    [["title", "category", "rating", "ratings_count", "final_price"]]
    .sort_values(
        ["rating", "ratings_count"],
        ascending=[False, False]
    )
)

best_products.head(10)

                     title     category  rating  ratings_count  final_price
1082                 GUESS      watches     5.0             22       8900.0
44                    Soie       briefs     4.9             14        370.0
962                    Nun         tops     4.9             14       1495.0
293               Priyaasi     earrings     4.9             13        947.0
571   Dreamz by Pantaloons   nightdress     4.9             12        699.0
644        U.S. Polo Assn.       shirts     4.9             10       1399.0
189               WoowZerz      dresses     4.8             26       1247.0
178            COVER STORY      dresses     4.8             24       2094.0
1005    Allen Solly Junior  track-pants     4.8             14        749.0
1039        Arrow New York      tshirts     4.8             13        674.0

In [54]:
high_review_products = (
    df_clean[df_clean["ratings_count"] >= 50]
    [["title", "category", "rating", "ratings_count", "final_price"]]
    .sort_values(
        ["rating", "ratings_count"],
        ascending=[False, False]
    )
)

high_review_products.head(10)

               title      category  rating  ratings_count  final_price
728            Arrow        shirts     4.7             64       1199.0
42        Van Heusen        briefs     4.6            192        649.0
735            Levis        shirts     4.6            168       2079.0
508         HERE&NOW         jeans     4.6            111        767.0
457  U.S. Polo Assn.       jackets     4.6             85       3134.0
933        Berrylush          tops     4.6             75       1299.0
814           Campus  sports-shoes     4.6             71        909.0
229        SASSAFRAS       dresses     4.5           4441        769.0
297         Priyaasi      earrings     4.5            347        500.0
80   PUMA Motorsport  casual-shoes     4.5            157       4199.0

In [55]:
category_reviews = (
    df_clean.groupby("category")
    .agg(
        product_count=("product_id", "count"),
        total_reviews=("ratings_count", "sum")
    )
    .sort_values("total_reviews", ascending=False)
)

category_reviews.head(10)

              product_count  total_reviews
category
dresses                 100          15462
shirts                   97           6085
tops                    122           5077
jeans                    57           4837
tshirts                  39           4715
sports-shoes             51           3243
sweaters                 34           3060
jackets                  29           2991
earrings                 34           2574
watches                  15           2198

# Final Summary — Ecommerce Dataset

## Dataset Overview

The Ecommerce Dataset contains product information collected across 98 category-specific CSV files.

All 98 files had the same 24-column structure. After combining the files, the dataset contained 2,000 rows.

During data cleaning, 1,000 exact duplicate rows were identified and removed, resulting in 1,000 unique products.

## Data Cleaning

The following cleaning steps were performed:

- Combined all 98 CSV files into one DataFrame.
- Verified that all files had the same column structure.
- Removed exact duplicate records.
- Converted `final_price` from text to numeric format.
- Checked missing values across all columns.
- Kept missing values in optional fields instead of replacing them with artificial values.
- Reviewed the `discount` column and retained its missing values because a missing discount does not necessarily mean a 0% discount.

## Category Analysis

The dataset contains 97 product categories.

The categories with the highest number of products were:

- Tops — 122 products
- Dresses — 100 products
- Shirts — 97 products
- Jeans — 57 products
- Sports-shoes — 51 products

The top three categories alone represented 31.9% of the 1,000 unique products.

## Price Analysis

The average final price across products varied considerably between categories.

Among categories with at least 10 products:

- Watches had the highest average final price at approximately ₹5,393.
- Sports-shoes followed with approximately ₹4,228.
- Sweatshirts averaged approximately ₹2,839.
- Jeans averaged approximately ₹2,174.
- Kurtas averaged approximately ₹1,919.

Categories with very few products were excluded from the reliable category comparison because their averages could be misleading.

## Rating Analysis

The overall average product rating was approximately 3.62 out of 5.

Among categories with at least 10 products:

- Watches had the highest average rating at approximately 4.15.
- Sweaters followed at approximately 4.15.
- Sports-shoes averaged approximately 4.12.
- Handbags averaged approximately 4.10.

This shows that some categories combine relatively high prices with strong customer ratings.

## Discount and Price Analysis

Correlation analysis showed:

- Initial price vs final price: approximately 0.80
- Discount vs final price: approximately -0.07
- Discount vs initial price: approximately 0.14

The strong positive relationship between initial price and final price indicates that higher-priced products generally have higher final prices.

The very weak relationship between discount and final price indicates that discount percentage alone does not strongly determine the final price.

Some products also contained discount values while their initial and final prices were identical. This was identified as a potential data-quality issue.

## Rating and Review Analysis

The correlation between rating and ratings count was approximately 0.13.

This represents a very weak positive relationship.

Therefore, products with more reviews do not necessarily have much higher ratings.

## Product-Level Analysis

Products with high ratings were analyzed using minimum review-count thresholds.

When requiring at least 10 reviews, several products had ratings between 4.8 and 5.0.

A stricter analysis using at least 50 reviews showed that:

- Arrow shirts had a rating of 4.7 with 64 reviews.
- Van Heusen briefs had a rating of 4.6 with 192 reviews.
- SASSAFRAS dresses had a rating of 4.5 with 4,441 reviews.

This demonstrated that rating count should also be considered when evaluating highly rated products.

## Customer Engagement by Category

Dresses had the highest total number of reviews with 15,462 reviews.

Other highly reviewed categories included:

- Shirts — 6,085 reviews
- Tops — 5,077 reviews
- Jeans — 4,837 reviews
- Tshirts — 4,715 reviews

This indicates that dresses generated substantially more customer review activity than other categories in this dataset.

## Key Business Insights

1. Dresses have the highest number of products and the highest total number of reviews.
2. Watches have one of the highest average ratings and the highest average price among sufficiently large categories.
3. Higher initial prices generally correspond to higher final prices.
4. Discount percentage has very little relationship with final price.
5. Rating and review count have only a weak relationship.
6. A high rating should be considered together with review count rather than alone.
7. Some price and discount fields may contain inconsistencies and should be treated carefully.

## Conclusion

The Ecommerce dataset was cleaned, explored, and analyzed using Python and Pandas.

The analysis covered product categories, pricing, discounts, ratings, review counts, customer engagement, and data-quality issues.

The cleaned dataset provides a useful foundation for further analysis using SQL and for creating a business dashboard in Power BI.

In [56]:
%whos DataFrame

Variable                   Type         Data/Info
-------------------------------------------------
best_products              DataFrame    Shape: (670, 5)
category_price_analysis    DataFrame    Shape: (97, 2)
category_rating_analysis   DataFrame    Shape: (97, 2)
category_reviews           DataFrame    Shape: (97, 2)
df                         DataFrame    Shape: (2000, 24)
df_clean                   DataFrame    Shape: (1000, 24)
df_test                    DataFrame    Shape: (4, 24)
discount_price_analysis    DataFrame    Shape: (879, 3)
high_review_products       DataFrame    Shape: (280, 5)
rating_review_analysis     DataFrame    Shape: (1000, 2)
reliable_category_price    DataFrame    Shape: (26, 2)
reliable_category_rating   DataFrame    Shape: (26, 2)
temp                       DataFrame    Shape: (1, 24)

In [57]:
from pathlib import Path

output_path = Path("ecommerce_cleaned.csv")

df_clean.to_csv(output_path, index=False)

print("Export successful!")
print("File location:", output_path.resolve())
print("Rows exported:", len(df_clean))
print("Columns exported:", len(df_clean.columns))

Export successful!
File location: C:\Users\Kishan\OneDrive\Desktop\DataSets\Analysis\ecommerce_cleaned.csv
Rows exported: 1000
Columns exported: 24

In [58]:
import pandas as pd

check_df = pd.read_csv("ecommerce_cleaned.csv")

print(check_df.shape)
print(check_df.columns.tolist())

(1000, 24)
['product_id', 'title', 'product_description', 'rating', 'ratings_count', 'initial_price', 'discount', 'final_price', 'currency', 'images', 'delivery_options', 'product_details', 'breadcrumbs', 'product_specifications', 'amount_of_stars', 'what_customers_said', 'seller_name', 'sizes', 'videos', 'seller_information', 'variations', 'best_offer', 'more_offers', 'category']

In [59]:
# Count missing values in each column
null_counts = df_clean.isnull().sum()

# Show only columns that contain missing values
null_counts[null_counts > 0].sort_values(ascending=False)

videos                 781
what_customers_said    573
variations             562
seller_name            301
seller_information     301
discount               121
dtype: int64

In [60]:
rows_with_nulls = df_clean[df_clean.isnull().any(axis=1)]

print("Rows containing missing values:", len(rows_with_nulls))

display(rows_with_nulls.head(10))

Rows containing missing values: 990

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,8376765,Lino Perros,Women Navy Blue Solid Backpack,3.8,15,3995.0,58.0,3995.0,INR,http://assets.myntassets.com/assets/images/837...,...,"{""1_star"":2,""2_stars"":0,""3_stars"":3,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-8376765_cae700""]",NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
1,9136281,Tommy Hilfiger,Unisex Navy Blue Striped Backpack,4.5,67,2899.0,35.0,2899.0,INR,http://assets.myntassets.com/assets/images/913...,...,"{""1_star"":3,""2_stars"":4,""3_stars"":2,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]","[""rw-9136281_cae700""]",NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
2,17633752,Lavie,Aries Women Pink Mini Backpack,4.4,226,2999.0,65.0,2999.0,INR,http://assets.myntassets.com/assets/images/176...,...,"{""1_star"":9,""2_stars"":5,""3_stars"":10,""4_stars""...",NaN,NaN,"[{""size"":""S""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,"[{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
3,1376949,F Gear,Unisex Navy & Grey Printed Burner Backpack,4.4,1052,1675.0,52.0,1675.0,INR,http://assets.myntassets.com/assets/images/137...,...,"{""1_star"":33,""2_stars"":21,""3_stars"":69,""4_star...",NaN,NaN,"[{""size"":""Onesize""}]","[""https://videos.myntassets.com/assets/videos/...",NaN,NaN,{},"[{""offer_name"":""10% Instant Discount on Citi C...",backpacks
4,13939916,MYTRIDENT,Men Blue Solid Bath Robe,4.7,12,2899.0,17.0,2899.0,INR,http://assets.myntassets.com/assets/images/pro...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""M"",""value"":""45.0in"",""value_name"":""Fr...",NaN,NaN,"[{},{},{},{},{},{},{},{},{},{},{},{},{},{}]",{},"[{""offer_name"":""10% Instant Discount on IndusI...",bath-robe
5,19851824,AVI Living,Grey Solid 500 GSM Pure Cotton Bath Towel,4.0,5,1399.0,65.0,1399.0,INR,http://assets.myntassets.com/assets/images/198...,...,"{""1_star"":0,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Onesize""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bath-towels
6,17198778,H&M,Beige & Tan Solid Stoneware Soap Dispenser,4.5,42,1399.0,NaN,1399.0,INR,http://assets.myntassets.com/assets/images/171...,...,"{""1_star"":2,""2_stars"":2,""3_stars"":0,""4_stars"":...",NaN,H &███Hen███ & █████████eta█████████████████████,"[{""size"":""Onesize""}]",NaN,Pra███yat███fra█████████PVT███████████████████...,"[{},{}]","{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",bathroom-accessories
7,18602872,My Room,Yellow & Green Floral 140 TC King Bedsheet wit...,4.7,10,2999.0,54.0,2999.0,INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":0,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Single""},{""size"":""Double Queen""},{""s...",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
8,18602850,My Room,Ethnic Print 144 TC Super King Bedsheet with 2...,4.5,22,2999.0,54.0,2999.0,INR,http://assets.myntassets.com/assets/images/186...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":1,""4_stars"":...",NaN,NaN,"[{""size"":""Super King""}]",NaN,NaN,[{}],{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets
9,8961147,Story@home,Pink & White Floral 160 TC Cotton 1 King Bedsh...,3.7,7,2199.0,53.0,2199.0,INR,http://assets.myntassets.com/assets/images/896...,...,"{""1_star"":1,""2_stars"":1,""3_stars"":0,""4_stars"":...",NaN,NaN,"[{""size"":""Double King""}]",NaN,NaN,"[{},{}]",{},"[{""offer_name"":""10% Instant Discount on Citi C...",bedsheets

In [61]:
df_clean[df_clean["images"].isnull()]

Empty DataFrame
Columns: [product_id, title, product_description, rating, ratings_count, initial_price, discount, final_price, currency, images, delivery_options, product_details, breadcrumbs, product_specifications, amount_of_stars, what_customers_said, seller_name, sizes, videos, seller_information, variations, best_offer, more_offers, category]
Index: []

[0 rows x 24 columns]